### ISSUE TITLE
News Post

### ISSUE THREAD

**Issue by northbranding** [northbranding/TIAW#20]
We've edited one of the news posts (most left) on this page: https://demoplatform.net/tiaw_new/news/

But we are unable. to change the main photo. Would you be able to tell us where to do that?

**Comment by markendley** [comment]
you mean the featured image?

<img width="2515" alt="Screenshot 2024-12-17 at 9 15 51 am" src="https://github.com/user-attachments/assets/6e24dc50-9bba-41e1-98d9-c43aaadc09c0" />

**Comment by markendley** [comment]
just hover over it and then you'll see the buttons

<img width="1228" alt="Screenshot 2024-12-17 at 9 16 21 am" src="https://github.com/user-attachments/assets/c5586bed-ba87-4764-81ca-e800a8834517" />

**Comment by northbranding** [comment]
Thanks Mark! 

We see notifications that there are invalid blocks of content like below. Can you tell us why this is happening? 

![Screenshot 2024-12-17 at 11 08 17 AM](https://github.com/user-attachments/assets/ede617d1-c518-46f7-b7bc-a9d721c081e1)

**Comment by markendley** [comment]
It looks like you've copy and pasted the copy from another webpage?

Sometimes when you do that you copy/paste the html tags.

**Comment by northbranding** [comment]
I pasted it from a word doc and stripped out the formatting

**Comment by markendley** [comment]
When I checked there were some broken html tags

**Comment by northbranding** [comment]
All good, thanks for checking!
