### ISSUE TITLE
News Block

### ISSUE THREAD

**Issue by northbranding** [northbranding/TIAW#24]
It Seems the preview of the news block pulls quote a lot of text, is it possible to put a field for us to insert the preview text?
<img width="682" alt="Screenshot 2024-12-18 at 5 29 01 PM" src="https://github.com/user-attachments/assets/2508b70b-da63-4037-aa7e-78af9094c7c7" />

**Comment by markendley** [comment]
This one

<img width="1904" alt="Screenshot 2024-12-18 at 5 36 50 pm" src="https://github.com/user-attachments/assets/50bd91ea-5ef2-44bc-9939-48c76cb5561f" />

**Comment by northbranding** [comment]
Thanks Mark! 

We've added 3 News posts but can only see two on the page:
https://demoplatform.net/tiaw_new/news/

**Comment by markendley** [comment]
fixed

**Comment by northbranding** [comment]
Thanks Mark, Is it possible to make the Heading of the News block link to the article at the moment, you can only access the article by clicking the thumbnail

**Comment by markendley** [comment]
done
