### ISSUE TITLE
Pages not updating properly, maybe being cached?

### ISSUE THREAD

**Issue by northbranding** [northbranding/TIAW#26]
We are having issues with [this page ](https://demoplatform.net/tiaw_new/about/who-we-are/)in particular, we are making changes to the backend that are not being reflected in the front end. IT does for the preview, but then reverts back.

**Comment by markendley** [comment]
I just did a test and everything works fine. All I did was make the change and then click save.

Can you show me a screenshot of what's not updating?

**Comment by northbranding** [comment]
These two are not reflecting the changes

<img width="845" alt="Screenshot 2024-12-19 at 9 11 28 AM" src="https://github.com/user-attachments/assets/dbf83fbb-9483-48d3-bcf4-e52fc6eabbd2" />

**Comment by markendley** [comment]
everything's seems to be in order

<img width="929" alt="Screenshot 2024-12-19 at 10 55 02 am" src="https://github.com/user-attachments/assets/abd2c91f-7cf0-4790-90e2-6bdb61901be9" />


<img width="874" alt="Screenshot 2024-12-19 at 10 54 42 am" src="https://github.com/user-attachments/assets/3c0bc9d3-87ef-4141-8206-4e3ffc710475" />


I also changed the text in  those fields and the front-end updated. The fields are working fine.

**Comment by northbranding** [comment]
OH my gosh, can't believe I didn't see that *facepalm* thanks so much for being patient with me
